
package com.example.buycookies.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFC4933F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFF0D9)
val md_theme_light_onPrimaryContainer = Color(0xFF3E001E)
val md_theme_light_secondary = Color(0xFFA54E02)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5CCA8)
val md_theme_light_onSecondaryContainer = Color(0xFF2B151C)
val md_theme_light_tertiary = Color(0xFF7C5635)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCC2)
val md_theme_light_onTertiaryContainer = Color(0xFF2E1500)
val md_theme_light_error = Color(0xFFBA7A1A)
val md_theme_light_errorContainer = Color(0xFFFFEBD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1B)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A1B)
val md_theme_light_surfaceVariant = Color(0xFFF2ECDD)
val md_theme_light_onSurfaceVariant = Color(0xFF514347)
val md_theme_light_outline = Color(0xFF837377)
val md_theme_light_inverseOnSurface = Color(0xFFFAEEEF)
val md_theme_light_inverseSurface = Color(0xFF352F30)
val md_theme_light_inversePrimary = Color(0xFFFFDBB0)
val md_theme_light_surfaceTint = Color(0xFF986940)
val md_theme_light_outlineVariant = Color(0xFFD5CDC2)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFE5B0)
val md_theme_dark_onPrimary = Color(0xFF5E3511)
val md_theme_dark_primaryContainer = Color(0xFF7B5D29)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFF1D9)
val md_theme_dark_secondary = Color(0xFFE2D4BD)
val md_theme_dark_onSecondary = Color(0xFF422931)
val md_theme_dark_secondaryContainer = Color(0xFF5A4F3F)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFEED9)
val md_theme_dark_tertiary = Color(0xFFEFBD94)
val md_theme_dark_onTertiary = Color(0xFF48290C)
val md_theme_dark_tertiaryContainer = Color(0xFF623F20)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE7C2)
val md_theme_dark_error = Color(0xFFFFD9AB)
val md_theme_dark_errorContainer = Color(0xFF935800)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFEDD6)
val md_theme_dark_background = Color(0xFF201A1B)
val md_theme_dark_onBackground = Color(0xFFEBE7E0)
val md_theme_dark_surface = Color(0xFF201A1B)
val md_theme_dark_onSurface = Color(0xFFEBE6E0)
val md_theme_dark_surfaceVariant = Color(0xFF514347)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5CDC2)
val md_theme_dark_outline = Color(0xFF9E978C)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1B)
val md_theme_dark_inverseSurface = Color(0xFFEBE6E0)
val md_theme_dark_inversePrimary = Color(0xFF987540)
val md_theme_dark_surfaceTint = Color(0xFFFFE2B0)
val md_theme_dark_outlineVariant = Color(0xFF514C43)
val md_theme_dark_scrim = Color(0xFF000000)
